services:
  app:
    image: ${APP_SERVICE_IMAGE}:${APP_SERVICE_VERSION}
    ports:
      - "${APP_SERVICE_PORT}:${APP_SERVICE_PORT}"
    environment:
      - MODEL_SERVICE_URL=http://model-service:${MODEL_SERVICE_PORT}
      - APP_VERSION=${APP_SERVICE_VERSION}
    env_file:
      - .env
    volumes:
      - app-logs:/var/log/app
    restart: always
#    depends_on:
#      - model-service



volumes:
  app-logs:
#  model-cache:

#secrets:
#  model-credentials:
#    file: ./secrets/model_credentials.txt