services:
  app:
    image: ${APP_SERVICE_IMAGE}:${APP_SERVICE}
    # this is the only service exposed to the host.
    ports:
      - "${APP_SERVICE_PORT}:${APP_SERVICE_PORT}"
    environment:
      # communication happens over Docker's internal network using the service name.
      - MODEL_SERVICE_URL=http://model-service:${MODEL_SERVICE_PORT}
      - APP_SERVICE=${APP_SERVICE}
    env_file:
      - .env
    volumes:
      - app-logs:/var/log/app
    restart: always
    depends_on:
      - model-service
    secrets:
      - model_credentials

  model-service:
    image: ${MODEL_SERVICE_IMAGE}:${MODEL_SERVICE_VERSION}
    env_file:
      - .env
    volumes:
      - model-cache:/model-cache
    restart: always
    secrets:
      - model_credentials

volumes:
  app-logs:
  model-cache:
secrets:
  model_credentials:
    file: ./secrets/model_credentials.txt
