{
 "title": "Restaurant Sentiment Dashboard",
 "time": { "from": "2025-05-24T21:24:56.544Z", "to": "2025-05-24T23:15:51.840Z" },
 "panels": [
  {
   "title": "Grafana memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total review requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sentiment_app_requests_total{instance=\"10.244.0.22:5001\"}",
     "legendFormat": "Total Review Requests"
    }
   ]
  },
  {
   "title": "Review Length Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sentiment_app_review_length{instance=\"10.244.0.22:5001\"}",
     "legendFormat": "Review Length"
    }
   ]
  },
  {
   "title": "Prometheus Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentiment app review length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sentiment_app_review_length{instance=\"10.244.0.22:5001\"}",
     "legendFormat": "Review Length"
    }
   ]
  }
 ]
}