apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-model-service
spec:
  hosts:
    - {{ include "restaurant-sentiment.fullname" . }}-model
  http:
    - match:
        - sourceLabels:
            version: v2
      route:
        - destination:
            host: {{ include "restaurant-sentiment.fullname" . }}-model
            subset: v2
    - match:
        - sourceLabels:
            version: v1
      route:
        - destination:
            host: {{ include "restaurant-sentiment.fullname" . }}-model
            subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-model-dr
spec:
  host: {{ include "restaurant-sentiment.fullname" . }}-model
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2