apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/remla25-team7/app:latest
        ports:
        - containerPort: 5001
        env:
        - name: MODEL_SERVICE_URL
          value: "http://model-service:8080"
        - name: APP_VERSION
          value: "latest"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/app
      volumes:
      - name: log-volume
        emptyDir: {}