{{- if .Values.rateLimiting.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rateLimiting.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rateLimiting.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.rateLimiting.serviceName }}
    spec:
      containers:
        - name: ratelimit
          image: envoyproxy/ratelimit:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config-volume
              mountPath: /data
          env:
            - name: RATELIMIT_USE_STATSD
              value: "false"
            - name: LOG_LEVEL
              value: debug
            - name: RUNTIME_ROOT
              value: /data
            - name: RUNTIME_SUBDIRECTORY
              value: ratelimit
            - name: RUNTIME_WATCH_ROOT
              value: "false"
      volumes:
        - name: config-volume
          configMap:
            name: ratelimit-config
{{- end }}
