{{- if .Values.rateLimiting.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rateLimiting.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.rateLimiting.servicePort }}
      targetPort: 8081
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.rateLimiting.serviceName }}
{{- end }}
