apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoke-app
  template:
    metadata:
      labels:
        app: smoke-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smoke-app
spec:
  type: LoadBalancer
  selector:
    app: smoke-app
  ports:
  - port: 80
    targetPort: 80
