apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alertmanager.fullname }}-alertmanager-secret
  namespace: monitoring
type: Opaque
stringData:
  smtpPassword: {{ .Values.alertmanager.email.authPassword | quote }}
