apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  namespace: {{ .Values.prometheus.namespace | default "monitoring" }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics


