apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy-monitor
  namespace: istio-system
  labels:
    release: prometheus
    portName: http-web
spec:
  selector:
    matchExpressions:
      - key: sidecar.istio.io/status
        operator: Exists
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
