apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sentiment-app-alerts
  labels:
    release: prometheus
spec:
  groups:
    - name: app.rules
      rules:
        - alert: RequestCountReached
          expr: sentiment_app_requests_total >= 5
          for: 10s  # Optional: ensures value stays >= 5 for at least 10s
          labels:
            severity: warning
          annotations:
            summary: "Total requests reached threshold"
            description: "The sentiment app has received 5 or more total requests."


# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: sentiment-app-alerts
#   labels:
#     release: prometheus
# spec:
#   groups:
#   - name: app.rules
#     rules:
#     - alert: HighRequestRate
#       expr: rate(sentiment_app_requests_total[1m]) > 15
#       for: 2m
#       labels:
#         severity: warning
#       annotations:
#         summary: "High request rate detected"



