apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: model-cache
  name: model-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
