app:
  image: ghcr.io/remla25-team7/app:latest
  imagePullPolicy: Always
  port: 5001
  host: app.local
  

modelService:
  image: ghcr.io/remla25-team7/model-service:latest
  imagePullPolicy: Always
  port: 8080
  host: model.local

monitoring:
  enabled: true
  scrapeInterval: 15s
  appRequestRateThreshold: 15
  appRequestRateDuration: 2m

# AlertManager configuration for email alerts
alertmanager:
  enabled: true
  fullname: kube-prometheus-stack
  email:
    to: 'to-mail@gmail.com'
    from: 'from-mail@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    authUsername: 'from-mail@gmail.com'
    requireTLS: true
