app:
  imagePullPolicy: Always
  port: 5001
  host: app.local
  name: sentiment-app
  versions:
    - version: v1
      replicas: 1
      image: ghcr.io/remla25-team7/app:v0.0.8  # Without confidence - older version
    - version: v2
      replicas: 1
      image: ghcr.io/remla25-team7/app:v0.1.0  # With confidence - newer version
  
  # Traffic management configuration
  traffic:
    weights:
      v1: 60  # 60% of traffic to v1
      v2: 40  # 40% of traffic to v2

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  # Secrets configuration
  apiKey: "restaurant_sentiment_api_key_2024"
  modelServiceApiKey: "model_service_api_key"
  dbPassword: "secure_db_password_2024"
  externalApiSecret: "external_api_secret_key"

modelService:
  imagePullPolicy: Always
  port: 5000
  host: model.local
  name: sentiment-model
  versions:
    - version: v1
      replicas: 1
      image: ghcr.io/remla25-team7/model-service:0.2.22  # Without confidence scores (using latest for now)
    - version: v2
      replicas: 1
      image: ghcr.io/remla25-team7/model-service:0.3.0  # With confidence scores
  
  secret:
    modelCredentials: "thisIsTheSecret="

  modelUrl: "https://github.com/remla25-team7/model-training/releases/latest/download/model.pkl"
  vectorizerUrl: "https://github.com/remla25-team7/model-training/releases/latest/download/vectorizer.pkl"

  apiTimeout: "30"
  maxRequestSize: "16MB"

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

prometheus:
  namespace: "monitoring"
  ingress:
    enabled: true
    host: prometheus.local

grafana:
  ingress:
    enabled: true
    host: grafana.local

monitoring:
  enabled: true
  scrapeInterval: 15s
  appRequestRateThreshold: 15
  appRequestRateDuration: 2m

alertmanager:
  enabled: true
  fullname: kube-prometheus-stack
  smtpHost: smtp.gmail.com:587
  smtpFrom: 'from-mail@gmail.com'
  smtpUsername: 'from-mail@gmail.com'
  smtpPassword: 'password'
  smtpTo: 'to-mail@gmail.com'

sharedVolumePath: /vagrant/shared
