app:
  image: ghcr.io/remla25-team7/app:release
  port: 5001
  host: app.local

modelService:
  image: ghcr.io/remla25-team7/model-service:latest
  port: 8080
  host: model.local

monitoring:
  enabled: true
  scrapeInterval: 15s
  appRequestRateThreshold: 15
  appRequestRateDuration: 2m