app:
  image: ghcr.io/remla25-team7/app:latest
  imagePullPolicy: Always
  port: 5001
  host: app.local
  name: sentiment-app
  version: "latest"
  environment: "production"
  logLevel: "info"
  replicas: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"


modelService:
  image: ghcr.io/remla25-team7/model-service:latest
  imagePullPolicy: Always
  port: 5000
  host: model.local
  name: sentiment-model
  modelVersion: "latest"
  environment: "production"
  logLevel: "info"
  replicas: 1
  secret:
    modelCredentials: "thisIsTheSecret="

  modelUrl: "https://github.com/remla25-team7/model-training/releases/latest/download/model.pkl"
  vectorizerUrl: "https://github.com/remla25-team7/model-training/releases/latest/download/vectorizer.pkl"

  apiTimeout: "30"
  maxRequestSize: "16MB"

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

prometheus:
  namespace: "monitoring"

monitoring:
  enabled: true
  scrapeInterval: 15s
  appRequestRateThreshold: 15
  appRequestRateDuration: 2m

alertmanager:
  enabled: true
  fullname: kube-prometheus-stack
  smtpHost: smtp.gmail.com:587
  smtpFrom: 'from-mail@gmail.com'
  smtpUsername: 'from-mail@gmail.com'
  smtpPassword: 'password'
  smtpTo: 'to-mail@gmail.com'

sharedVolumePath: /vagrant/shared
