apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
      version: v2
  template:
    metadata:
      labels:
        app: model-service
        version: v2
    spec:
      containers:
        - name: model-service
          image: {{ .Values.modelService.image }}
          imagePullPolicy: {{ .Values.modelService.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.modelService.port }}
          env:
            - name: MODEL_SERVICE_PORT
              value: "{{ .Values.modelService.port }}"
