- name: Set up Kubernetes Controller
  hosts: ctrl
  become: yes
  tasks:
    # Step 13: Initialize the Kubernetes Cluster
    - name: Check if the admin.conf file exists
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeinit

    - name: Initialize the Kubernetes cluster
      command: kubeadm init --apiserver-advertise-address=192.168.56.100 --pod-network-cidr=10.244.0.0/16 --node-name ctrl
      when: not kubeinit.stat.exists
      ignore_errors: yes  # Ignore errors to continue execution if already initialized

    # Step 14: Setup kubectl for vagrant user
    - name: Create .kube directory for vagrant user
      file:
        path: "/home/vagrant/.kube"
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0777
    
    - name: Copy admin.conf to vagrant kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0777

    - name: Copy kubeconfig to shared folder for host access
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /vagrant/kubeconfig
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0777

    # Set KUBECONFIG for kubectl usage
    - name: Set the kubeconfig environment variable
      shell: export KUBECONFIG=/home/vagrant/.kube/config
      become_user: vagrant

    # Step 15: Create Pod Network
    - name: Download the Flannel YAML file
      get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/v0.26.7/Documentation/kube-flannel.yml
        dest: /tmp/kube-flannel.yml

    - name: Edit the Flannel YAML to configure the correct network interface
      lineinfile:
        path: /tmp/kube-flannel.yml
        insertafter: '^ *- --kube-subnet-mgr'
        line: '        - --iface=eth1'

    - name: Delete old Flannel DaemonSet if it exists
      command: kubectl delete daemonset kube-flannel-ds -n kube-flannel
      ignore_errors: yes
      become_user: vagrant

    - name: Apply Flannel network plugin
      command: kubectl apply -f /tmp/kube-flannel.yml
      become_user: vagrant

    # Step 16: Install Helm
    - name: Install Helm
      apt:
        name: helm
        state: present
        update_cache: yes

    - name: Verify Helm installation
      command: helm version

    - name: Remove temporary Flannel YAML file
      file:
        path: /tmp/kube-flannel.yml
        state: absent
