- name: Set up Kubernetes Controller
  hosts: ctrl
  become: yes
  vars:
    kubeinit_out: /vagrant/kubeinit.out
  tasks:
    # Step 13: Initialize the Kubernetes Cluster
    - name: Check if the admin.conf file exists
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeinit

    - name: Run kubeadm init and save its output
      command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.100
        --apiserver-cert-extra-sans=192.168.56.100
        --pod-network-cidr=10.244.0.0/16
      register: kubeinit_out
      args:
        creates: /etc/kubernetes/admin.conf
      become: yes


    - name: Generate a fresh kubeadm join command
      shell: kubeadm token create --print-join-command --ttl 1h
      register: join_command
      become: yes

    - name: Write full join command to shared file (with containerd support)
      copy:
        content: "{{ join_command.stdout | trim  }} --cri-socket=unix:///run/containerd/containerd.sock\n"
        dest: /vagrant/join_command.sh
        mode: '0755'


    # Step 14: Setup kubectl for vagrant user
    - name: Create .kube directory for vagrant user
      file:
        path: "/home/vagrant/.kube"
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0777
    
    - name: Copy admin.conf to vagrant kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0777

    - name: Copy kubeconfig to shared folder for host access
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /vagrant/kubeconfig
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0777

    # Set KUBECONFIG for kubectl usage
    - name: Set the kubeconfig environment variable
      shell: export KUBECONFIG=/home/vagrant/.kube/config
      become_user: vagrant

    # Step 15: Create Pod Network
    - name: Download the Flannel YAML file
      get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/v0.26.7/Documentation/kube-flannel.yml
        dest: /tmp/kube-flannel.yml

    - name: Edit the Flannel YAML to configure the correct network interface
      lineinfile:
        path: /tmp/kube-flannel.yml
        insertafter: '^ *- --kube-subnet-mgr'
        line: '        - --iface=eth1'

    - name: Delete old Flannel DaemonSet if it exists
      command: kubectl delete daemonset kube-flannel-ds -n kube-flannel
      ignore_errors: yes
      become_user: vagrant

    - name: Apply Flannel network plugin
      command: kubectl apply -f /tmp/kube-flannel.yml
      become_user: vagrant

    # Step 16: Install Helm
    - name: Add Helm GPG key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm APT repository
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present

    - name: Update apt package cache (for Helm)
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Helm
      apt:
        name: helm
        state: present
        update_cache: yes

    - name: Verify Helm installation
      command: helm version

    - name: Remove temporary Flannel YAML file
      file:
        path: /tmp/kube-flannel.yml
        state: absent
    
    # Step 23: Install Istio
    - name: Download Istio 1.25.2
      ansible.builtin.get_url:
        url: https://github.com/istio/istio/releases/download/1.25.2/istio-1.25.2-linux-arm64.tar.gz
        dest: /home/vagrant/istio-1.25.2-linux-arm64.tar.gz
        mode: '0644'
        force: no

    - name: Unpack Istio archive
      ansible.builtin.unarchive:
        src: /home/vagrant/istio-1.25.2-linux-arm64.tar.gz
        dest: /home/vagrant/
        remote_src: yes

    - name: Copy istioctl binary to /usr/local/bin
      ansible.builtin.copy:
        src: /home/vagrant/istio-1.25.2/bin/istioctl
        dest: /usr/local/bin/istioctl
        remote_src: yes
        mode: '0755'
      become: yes

