- name: Join worker nodes to Kubernetes cluster
  hosts: kube_workers
  become: yes
  tasks:

    - name: Check if the node has already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join cluster (only if not already joined)
      command: "{{ hostvars['ctrl']['join_command'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
