- name: Join worker nodes to Kubernetes cluster
  hosts: node-1,node-2
  become: yes
  tasks:
    - name: Load join command from shared file
      slurp:
        src: /vagrant/join_command.sh
      register: join_file

    - name: Set join_command fact
      set_fact:
        join_command: "{{ join_file.content | b64decode }}"

    - name: Check if the node has already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join cluster (only if not already joined)
      shell: "{{ join_command }}"
      when: not kubelet_conf.stat.exists
