- name: Join worker nodes to Kubernetes cluster
  hosts: node
  become: yes
  tasks:
    - name: Get join command from controller (delegate to ctrl)
      command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      changed_when: false

    - name: Join cluster (skip if already joined)
      command: "{{ join_command.stdout }}"
      when: "'kubelet' not in ansible_facts.services"