- name: Join worker nodes to Kubernetes cluster
  hosts: nodes
  become: yes
  tasks:
    - name: Get join command from controller (delegate to ctrl)
      command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      changed_when: false

    - name: Check if the node has already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join cluster (only if not already joined)
      shell: "{{ join_command.stdout }}"
      when: not kubelet_conf.stat.exists