- name: Join worker nodes to Kubernetes cluster
  hosts: kube_workers
  become: yes
  tasks:

    - name: Check if the node has already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Wait for Kubernetes API server to become reachable
      when: not kubelet_conf.stat.exists
      uri:
        url: https://192.168.56.100:6443/version
        method: GET
        validate_certs: no
        status_code: 200
      register: api_result
      until: api_result.status == 200
      retries: 30
      delay: 5

    - name: Wait for join command to be present
      when: not kubelet_conf.stat.exists
      wait_for:
        path: /vagrant/join_command.sh
        state: present
        timeout: 90

    - name: Read join command from file
      when: not kubelet_conf.stat.exists
      slurp:
        src: /vagrant/join_command.sh
      register: join_script_raw

    - name: Decode join command
      when: not kubelet_conf.stat.exists
      set_fact:
        join_command_decoded: "{{ join_script_raw.content | b64decode | trim }}"

    - name: Join cluster
      when: not kubelet_conf.stat.exists
      shell: "{{ join_command_decoded }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
