apiVersion: v1
kind: Service
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "restaurant-sentiment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/version: {{ .Values.app.version | default "1.0.0" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.app.port | quote }}
    prometheus.io/path: "/metrics"
    description: "Restaurant Sentiment Analyzer Web Application"
spec:
  selector:
    app.kubernetes.io/name: {{ include "restaurant-sentiment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
