apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: sentiment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-app
  template:
    metadata:
      labels:
        app: sentiment-app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: app-secret
