{{- if not .Values.trafficManagement.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "restaurant-sentiment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant-sentiment.fullname" . }}-app
                port:
                  number: {{ .Values.app.port }}
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: {{ include "restaurant-sentiment.fullname" . }}-app
                port:
                  number: {{ .Values.app.port }}
{{- end }}
--- 
# Prometheus Ingress
{{- if .Values.prometheus.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.prometheus.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
{{- end }}



--- 
# Grafana Ingress
{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.grafana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
{{- end }}

