apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.modelService.name }}-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.modelService.name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.modelService.name }}
        version: v2
    spec:
      containers:
        - name: {{ .Values.modelService.name }}
          image: {{ .Values.modelService.image }}
          imagePullPolicy: {{ .Values.modelService.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.modelService.port }}
          env:
            - name: MODEL_SERVICE_PORT
              value: "{{ .Values.modelService.port }}"
