apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
      version: v2
  template:
    metadata:
      labels:
        app: model-service
        version: v2
    spec:
      containers:
      - name: model-service
        image: {{ .Values.modelService.image }}
        ports:
        - containerPort: 5000 