apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-model-service
spec:
  hosts:
    - {{ include "restaurant-sentiment.fullname" . }}-model
  http:
    - match:
        - headers:
            x-user-id:
              exact: "test-user"
      route:
        - destination:
            host: {{ include "restaurant-sentiment.fullname" . }}-model
            subset: v2
          weight: 100
    - route:
        - destination:
            host: {{ include "restaurant-sentiment.fullname" . }}-model
            subset: v1
          weight: 90
        - destination:
            host: {{ include "restaurant-sentiment.fullname" . }}-model
            subset: v2
          weight: 10