apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sentiment-app-alerts
  labels:
    release: prometheus
spec:
  groups:
  - name: app.rules
    rules:
    - alert: HighRequestRate
      expr: rate(sentiment_app_requests_total[1m]) > 15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High request rate detected"
