apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelService.name }}
  labels:
    app: {{ .Values.modelService.name }}
spec:
  selector:
    app: {{ .Values.modelService.name }}
  ports:
    - name: http
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  type: ClusterIP
