apiVersion: v1
kind: Service
metadata:
  name: sentiment-app
  labels:
    app: sentiment-app
spec:
  selector:
    app: app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: ClusterIP