apiVersion: v1
kind: Service
metadata:
  name: sentiment-model
  labels:
    app: sentiment-model
spec:
  selector:
    app: model-service
  ports:
    - name: http
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  type: ClusterIP