apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-shared-secret
type: Opaque
data:
  model_credentials: {{ .Values.modelService.secret.modelCredentials | b64enc | quote }}
