apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-model-env-config
  labels:
    app.kubernetes.io/name: {{ include "restaurant-sentiment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model
data:
  MODEL_SERVICE_NAME: "Sentiment Analysis Model"
  MODEL_VERSION: "{{ .Values.modelService.modelVersion }}"
  MODEL_URL: "{{ .Values.modelService.modelUrl }}"
  VECTORIZER_URL: "{{ .Values.modelService.vectorizerUrl }}"
  MODEL_PORT: "{{ .Values.modelService.port }}"
  APP_ENV: "{{ .Values.modelService.environment }}"
  LOG_LEVEL: "{{ .Values.modelService.logLevel }}"
  API_TIMEOUT: "{{ .Values.modelService.apiTimeout }}"
  MAX_REQUEST_SIZE: "{{ .Values.modelService.maxRequestSize }}"
  MODEL_CACHE_PATH: "/model-cache"
  ARTIFACTS_CACHE_PATH: "/tmp/artefacts"