apiVersion: v1
kind: Service
metadata:
  name: {{ include "restaurant-sentiment.fullname" . }}-model
  labels:
    app.kubernetes.io/name: {{ include "restaurant-sentiment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model
    app.kubernetes.io/version: {{ .Values.modelService.modelVersion | default "latest" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.modelService.port | quote }}
    prometheus.io/path: "/metrics"
    description: "Sentiment Analysis Model Service"
spec:
  selector:
    app.kubernetes.io/name: {{ include "restaurant-sentiment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: model
  ports:
    - name: http
      port: {{ .Values.modelService.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
